djtd/djapp/urls.py
from django.urls import path
from . import views

#为URL名称添加命名空间,方便项目中多应用的情况
app_name = 'djapp'

urlpatterns = [
    path('',views.index,name='index'),
    # #<int:question_id>捕获URL传入的整数型
    # path('<int:question_id>/',views.detail,name='detail'),
    #改变投票详情视图的URL
    path('specifics/<int:question_id>/',views.detail,name='detail'),
    path('<int:question_id>/results/',views.results,name='results'),
    path('<int:question_id>/vote/',views.vote,name='vote'),
]

djtd/djtd/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('djapp/',include('djapp.urls')),
]

djtd/djapp/models.py
from django.db import models
import datetime
from django.utils import timezone
# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    objects = models.Manager()

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    objects = models.Manager()

djtd/djapp/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,Http404,HttpResponseRedirect
from .models import Question,Choice
from django.template import loader
from django.shortcuts import render
from django.urls import reverse
# Create your views here.
#第一个视图
# def index(request):
#     return HttpResponse("Hehllo,world.")
#实验访问多个页面-------------
def detail(request,question_id):
#这里需要输入一个questionID进行查询
    # try:
    #     question = Question.objects.get(pk=question_id)
    # except Question.DoesNotExist:
    #     raise Http404("没有问题")
    # return render(request,'djapp/detail.html',{'question' : question})
    question = get_object_or_404(Question,pk=question_id)
    return render(request,'djapp/detail.html',{'question': question})

def results(request,question_id):
    response="you're looking at the results of question %s."
    return HttpResponse(response % question_id)

def vote(request,question_id):
    quetion = get_object_or_404(Question,pk = question_id)
    try:
        selected_choice = quetion.choice_set.get(pk=request.POST['choice'])
    except(KeyError,Choice.DoesNotExist):
        return render(request,'djapp/detail.html',{
            'question':quetion,
            'error_message':"upi dodm't select a choice",
        })
    else:
        selected_choice.votes +=1
        selected_choice.save()
        return HttpResponseRedirect(reverse('djapp:results',args=(question.id,)))
#--------------------------
#真正有用的视图----------------
#我们在 index() 函数里插入了一些新内容，
# 让它能展示数据库里以发布日期排序的最近 5 个投票问题，以空格分割：
def index(request):
    #展示数据库里以发布日期排序的最近5个内容，以空格分隔
    #增删改查——查
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    # #输出方式一：循环遍历输出数据前五条内容，以逗号分隔
    # output = ' , '.join([q.question_text for q in latest_question_list])
    # return HttpResponse(output)
    #输出方式二：上下文字典传递映射对象
    # template = loader.get_template('djapp/index.html')
    # context = {
    #     'latest_question_list': latest_question_list,
    # }
    # return HttpResponse(template.render(context,request))
    #输出方式三：render():django提供了一个用作【载入末班，填充上下文，再返回由它生成httpresponse对象】的函数
    context = {'latest_question_list':latest_question_list}
    return render(request,'djapp/index.html',context)
#------------------------------

djtd/djapp/templates/djapp/detail.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>sss</title>
    </head>
    <body>
        <h1>{{ question.question_text }}</h1>
        {%if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

        <form action="{% url 'djapp:vote' question.id %}" method="POST">
            {% csrf_token %}
            {% for choice in question.choice_set.all %}
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{choice.id}}">
                <label for="choice{{ forloop.counter }}">{{ choice.choice_text}}</label><br>
                {% endfor %}
                <input type="submit" value="Vote">
        </form>
        <ul>
        {% for choice in question.choice_set.all %}
            <li>{{ choice.choice_text }}</li>
        {% endfor %}
        </ul>
    </body>
</html>

djtd/djapp/templates/djapp/indes.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>sss</title>
    </head>
    <body>
        {% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
    </body>
</html>

djtd/djapp/templates/djapp/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>sss</title>
    </head>
    <body>
        {% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
    <!-- 对于一个包含多个应用的项目，使用url链接 -->
        <li><a href="{% url 'djapp:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
    </body>
</html>